{{- $root := . -}}
{{range $name, $collector := .Values.collector }}
{{- if $collector.serviceaccount.create  }}
{{ $resourceName := printf "%s-%s-sa-collector" (include "finala.fullname" $root) $name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $resourceName }}
{{- if $collector.serviceaccount.annotations }}
  annotations: 
{{ toYaml $collector.serviceaccount.annotations | indent 4 }}
{{- end }}

{{- end }}
{{- end }}