{{- if .Values.notifier.create  }}
{{- if .Values.notifier.serviceaccount.create  }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.notifier.serviceaccount.annotations }}
  annotations: 
{{ toYaml .Values.notifier.serviceaccount.annotations | indent 4 }}
{{- end }}
  name: {{ include "finala.fullname" . }}-sa-notifier
{{- end -}}
{{- end -}}