{{- if .Values.api.create  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finala.fullname" . }}-api
  labels:
{{ include "finala.labels" . | indent 4 }}
    component: {{ include "finala.fullname" . }}-api
  annotations:
{{- if .Values.api.annotations }}
{{ toYaml .Values.api.annotations | indent 4}}
{{- end }}
{{ include "finala.annotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "finala.matchLabels" . | indent 6 }}
      component: {{ include "finala.fullname" . }}-api
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
{{ include "finala.labels" . | indent 8 }}
        component: {{ include "finala.fullname" . }}-api
      annotations:
{{- if .Values.api.annotations }}
{{ toYaml .Values.api.annotations | indent 8}}
{{- end }}
    spec:
{{- if .Values.api.serviceaccount.create  }}
      serviceAccountName: {{ include "finala.fullname" . }}-sa-api
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          args: ["api"]
          volumeMounts:
            - name: {{ include "finala.fullname" . }}-configmap-api
              mountPath: /etc/finala
      volumes:
        - name: {{ include "finala.fullname" . }}-configmap-api
          configMap:
            name: {{ include "finala.fullname" . }}-configmap-api
            items:
              - key: config
                path: config.yaml

{{- end -}}
