{{- if .Values.api.create  }}
{{- if .Values.api.serviceaccount.create  }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.api.serviceaccount.annotations }}
  annotations: 
{{ toYaml .Values.api.serviceaccount.annotations | indent 4 }}
{{- end }}
  name: {{ include "finala.fullname" . }}-sa-api
{{- end -}}
{{- end -}}